version: "2"

services:
  
  client:
    container_name: archival_material_client
    build: ./archival-material-client
    restart: always
    environment:
      - REACT_APP_API_URL="http://perun.fit.vutbr.cz:8080/api"
      - REACT_APP_PROXY_URL="http://perun.fit.vutbr.cz:8081"
    ports:
      - "8082:80"
      - "8090:443"
    volumes:
      - ./archival-material-client/node_modules:/app/node_modules
      - ./archival-material-client/nginx.conf:/etc/nginx/nginx.conf
      #- certbot-conf:/etc/letsencrypt
      #- certbot-www:/var/www/certbot
  
  #certbot:
  #  image: certbot/certbot
  #  container_name: certbot
  #  volumes:
  #    - certbot-conf:/etc/letsencrypt
  #    - certbot-www:/var/www/certbot
  #  command: certonly -v --webroot -w /var/www/certbot --force-renewal --email xsesta07@vutbr.cz -d perun.fit.vutbr.cz:8082 --agree-tos

#volumes:
#  certbot-conf:
#    driver: local
#  certbot-www:
#    driver: local

networks:
  archival_material_sys:  # Define the network
    driver: bridge
