openapi: 3.0.3
info:
  title: ELASTIC SEARCH REINDEXING REST API
  description: ELASTIC SEARCH REINDEXING REST API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /elastic-search/reindex:
    get:
      tags:
        - elastic-seach-controller
      operationId: reindex
      summary: Reindex elasticsearch database
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
        401:
          description: Unauthorized
        500:
          description: Internal server error
  /elastic-search/progress:
    get:
      tags:
        - elastic-seach-controller
      summary: Reindex elasticsearch database
      operationId: progress
      responses:
        200:
          content:
            application/json:
              schema:
                type: string
          description: OK
        401:
          description: Unauthorized
        500:
          description: Internal server error