

const WindowStateTypes = {

  TOGGLE_SIDE_PANEL_OPEN: 'TOGGLE_SIDE_PANEL_OPEN',
  TOGGLE_HELP_MODAL_OPEN: 'TOGGLE_HELP_MODAL_OPEN',
  TOGGLE_FILTER_PANEL_OPEN: 'TOGGLE_FILTER_PANEL_OPEN',
  TOGGLE_FULLSCREEN: 'TOGGLE_FULLSCREEN',
};

export default WindowStateTypes;
