

const ImageStateTypes = {

  ROTATE: 'IMAGE_STATE_ROTATE',
  TOGGLE_LOCK: 'IMAGE_STATE_TOGGLE_LOCK',
  RESET: 'IMAGE_STATE_RESET',
  MOVE: 'IMAGE_STATE_MOVE',
  UPDATE_POSITION: 'IMAGE_STATE_UPDATE_POSITION',
};

export default ImageStateTypes;
